### ISSUE TITLE
BlackBoard spider error

### ISSUE THREAD

**Issue by Lenvive** [HeZeBang/HollyDDL#1]
When logining blackboard, some errors appear and can't search the DDLs.
`urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='elearning.shanghaitech.edu.cn', port=8443): Max retries exceeded with url: /webapps/bb-BB-BBLEARN/index.jsp?ticket=ST-304asdafkqiYJJNhauujs-QORAsxvho-vA18ciapserver2 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))`

**Comment by HeZeBang** [comment]
Fixed at #3
