### ISSUE TITLE
[Blackboard] Timestamp error

### ISSUE THREAD

**Issue by HeZeBang** [HeZeBang/HollyDDL#4]
- Blackboard timestamp did added the time zone, but parsed twice in front-end. Thus leads to 8 hrs error.

**Comment by Lenvive** [comment]
It is because the `StrictMode` in index.tsx. This only takes effect in developement mode.

**Comment by HeZeBang** [comment]
This is not what I mean. The blackboard api returns a string format time, while our serverless function parses it using its own timezone. Then the timestamp is based on it's timezone. So this caused 8hrs error (from UTC to UTC+8)

This will be fixed in the next commit.
